### ISSUE TITLE
To parametrize text to check in `body.includes`

### ISSUE THREAD

**Issue by oscard0m** [bdougie/octoherd-script-validate-pr#3]
https://github.com/bdougie/octoherd-script-validate-pr/blob/68bfc39260add73ac350372da62c8f04174d67dd/script.js#L21-L22

I would be happy to pick it if it is ok to you but... what do you want to parametrize, the text? the function?

@bdougie

**Comment by bdougie** [comment]
Yes, that was the goal. I threw this together before jumping on the [github stream](https://www.twitch.tv/videos/1014382802), but yeah would love contributions to make this a broader use case.
