### ISSUE TITLE
What is the purpose of the script: Issues or PRs?

### ISSUE THREAD

**Issue by oscard0m** [bdougie/octoherd-script-validate-pr#5]
Text refers to PRs but interaction with GitHub API interacts with issues? Should the docs and repo be updated or code should be checking PRs instead of issues?

**Comment by bdougie** [comment]
Yes, that is a great question. I wrote this for my quick use case this morning. To label PRs in the https://github.com/github/gitignore repo, which has no issues. I have not taken account projects with actual issues, but would definitely like to consider those too.

Basically the goal this project is to enforce folks to not leave boiler TODO code.

**Comment by oscard0m** [comment]
> Yes, that is a great question. I wrote this for my quick use case this morning. To label PRs in the https://github.com/github/gitignore repo, which has no issues. I have not taken account projects with actual issues, but would definitely like to consider those too.
> 
> Basically the goal this project is to enforce folks to not leave boiler TODO code.

Yep, I think is interesting to consider both: `pr`'s and `issues`. But checking the code in (`main` branch at least), it is only considering issues, right?

https://github.com/bdougie/octoherd-script-validate-pr/blob/68bfc39260add73ac350372da62c8f04174d67dd/script.js#L12-L15

https://github.com/bdougie/octoherd-script-validate-pr/blob/68bfc39260add73ac350372da62c8f04174d67dd/script.js#L26

**Comment by oscard0m** [comment]
Hi @bdougie I just wanted to follow up on this issue. Is this something you built only for the retransmission or are you open to iterate this script? :)

**Comment by bdougie** [comment]
Hey sorry for the delay, but yes open to iteration. I would love for this to be useful for more than just my use case. 

Just performed a name change to reflect this in #10

**Comment by oscard0m** [comment]
I think this issue is clarified already. We should close this. @bdougie were you expecting any other action from this issue?
